### ISSUE TITLE
MQM8790-HS2F PSU status 

### ISSUE THREAD

**Issue by krtzr** [stanford-rc/ibswinfo#8]
Hi,

Thank you for this very useful tool! 

With our MQM8790-HS2F switches, I have the issue that none of them reports the presence of two PSUs, even though they are physically present. PSU1 reports "ERROR" for all of them (see below).

I wonder whether there is any real problem with them. Do you have any hints to follow up? - Thank you in advance!

``` =================================================
Quantum Mellanox Technologies
=================================================
part number        | MQM8790-HS2F
serial number      | MT2006X1....
ports              | 80
GUID               | 0x.....
firmware version   | 0.0000.0000
-------------------------------------------------
uptime (d-h:m:s)   | 389d-18:45:26
-------------------------------------------------
PSU0 status        | OK
     S/N           | MT1951X0....
     DC power      | OK
     fan status    | OK
     power (W)     | 198
PSU1 status        | ERROR
     DC power      | ERROR
     fan status    | ERROR
```

**Comment by kcgthb** [comment]
Hi @krtzr 
I suspect you may be using MFT 4.16, right? There is an issue with that release of the Mellanox Firmware Tools that prevents registers from being correctly retrieved. The main effect is that the reported firm,ware version is 0.000.000, and the 2nd PSU doesn't report its status correctly, as you noted. The problem should be fixed in the upcoming MFT 4.17.2 release (see #7).

**Comment by krtzr** [comment]
In fact, I am using MFT 4.17, but as already mentioned in  #7, that didn't solve the issue . Sorry, that I didn't realize that this issue is the same as #7 .
